server:
  port: 8083
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/plain
  servlet:
    context-path: /api/v1

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/prueba-tecnica-products
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
